"""empty message

Revision ID: 085c92c5e4b7
Revises: 255a8a9a1538
Create Date: 2022-06-01 14:44:18.294012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '085c92c5e4b7'
down_revision = '255a8a9a1538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('reference_no', sa.BigInteger(), nullable=False))
    op.drop_column('request', 'reference_no_')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('reference_no_', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('request', 'reference_no')
    # ### end Alembic commands ###
